# pylint: disable=missing-module-docstring
# pylint: disable=unused-import

from test_betterranker import TestBetterRanker
from test_binarylogisticregressionclassifier import \
    TestBinaryLogisticRegressionClassifier
from test_bloomfilter import TestBloomFilter
from test_booleansearchengine import TestBooleanSearchEngine
from test_compressedinmemorypostinglist import \
    TestCompressedInMemoryPostingList
from test_documentpipeline import TestDocumentPipeline
from test_dummyinmemoryinvertedindex import TestDummyInMemoryInvertedIndex
from test_dummynormalizer import TestDummyNormalizer
from test_dummytokenizer import TestDummyTokenizer
from test_editsearchengine import TestEditSearchEngine, TestMazunkiSearchEngine
from test_edittable import TestEditTable
from test_eliasgammacodec import TestEliasGammaCodec
from test_evaluationmetrics import TestEvaluationMetrics
from test_expressioncomposer import TestExpressionComposer
from test_extendedbooleansearchengine import TestExtendedBooleanSearchEngine
from test_inmemorycorpus import TestInMemoryCorpus
from test_inmemorydictionary import TestInMemoryDictionary
from test_inmemorydocument import TestInMemoryDocument
from test_inmemoryinvertedindexwithcompression import \
    TestInMemoryInvertedIndexWithCompression
from test_inmemoryinvertedindexwithoutcompression import \
    TestInMemoryInvertedIndexWithoutCompression
from test_inmemorypostinglist import TestInMemoryPostingList
from test_naivebayesclassifier import TestNaiveBayesClassifier
from test_nearestneighborclassifier import TestNearestNeighborClassifier
from test_pagerank import TestPageRank
from test_porternormalizer import TestPorterNormalizer
from test_postingsmerger import TestMazunki, TestPostingsMerger
from test_rocchioclassifier import TestRocchioClassifier
from test_shallowcaseextractor import TestShallowCaseExtractor
from test_shinglegenerator import TestShingleGenerator
from test_sieve import TestSieve
from test_similaritysearchengine import TestSimilaritySearchEngine
from test_simplenormalizer import TestSimpleNormalizer
from test_simpleranker import TestSimpleRanker
from test_simplesearchengine import (TestMazunkiSimpleSearchEngine,
                                     TestSimpleSearchEngine)
from test_simpletokenizer import TestSimpleTokenizer
from test_soundexnormalizer import TestSoundexNormalizer
from test_sparsedocumentvector import TestSparseDocumentVector
from test_stringfinder import TestStringFinder
from test_suffixarray import TestSuffixArray
from test_trie import TestTrie
from test_unigramtokenizer import TestUnigramTokenizer
from test_variablebytecodec import TestVariableByteCodec
from test_vectorizer import TestVectorizer
from test_wildcardexpander import TestWildcardExpander
from test_windowfinder import TestWindowFinder
from test_wordshinglegenerator import TestWordShingleGenerator
